### ISSUE TITLE
Setup Advisor problem

### ISSUE THREAD

**Issue by Hukyo66** [SeriousOldMan/Simulator-Controller#16]
Hello, 
when I click on problem button and then selet the problem type I have this 2 sequential errors.
What could it be
Thank you in advance.

![Immagine 2022-08-14 093846](https://user-images.githubusercontent.com/111219721/184527259-6f233936-cf98-4ae6-ac52-de6cb1e05d73.png)
![Immagine 2022-08-14 093955](https://user-images.githubusercontent.com/111219721/184527280-50b36a9c-30ab-49a6-a1ca-dd9e98cda561.png)

**Comment by SeriousOldMan** [comment]
Hi, I think, we solved that already on Discord. For everybody, that stumble over the same problem, here is the solution:

This problem is related to the compatibility setting of the browserr engine, which is built into Windows. Normally, the apps of Simulator Controller changes this setting in the Registry automatically, but sometimes this is prevented, for example by an Antivirus app.

Open the RegEdit and make sure, that the entry for the "Setup Advisor.exe" is present:

![image](https://user-images.githubusercontent.com/73251853/184654899-5cb96293-9be9-4edc-bb71-6da5dda6aad3.png)
