### ISSUE TITLE
Remove externally referenced image

### ISSUE THREAD

**Issue by cyb3rfox** [SeriousOldMan/Simulator-Controller#4]
Hi,

apparently you referenced a picture on one of our webservers in https://github.com/SeriousOldMan/Simulator-Controller/blob/5527572b7594d20c5f6f16a02ff2513fdc46a14c/Sources/Includes/Functions.ahk in line 794. That triggered our security monitoring. Please replace that picture with a local copy or a picture from a different server as soon as possible.
¨
Thank you very much,
Mat

**Comment by SeriousOldMan** [comment]
Hi Matthias,

 

sorry for the inconvenience. The code reference will be removed with the next release by the end of the week.

 

But since it was only used during the last easter holidays from Friday to Monday, no more requests will be issued anyway.

 

Best regards and Sorry

 

Oliver

 

Von: Mathias Fuchs ***@***.***> 
Gesendet: Dienstag, 6. April 2021 20:53
An: SeriousOldMan/Simulator-Controller ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [SeriousOldMan/Simulator-Controller] Remove externally referenced image (#4)

 

Hi,

apparently you referenced a picture on one of our webservers in https://github.com/SeriousOldMan/Simulator-Controller/blob/5527572b7594d20c5f6f16a02ff2513fdc46a14c/Sources/Includes/Functions.ahk in line 794. That triggered our security monitoring. Please replace that picture with a local copy or a picture from a different server as soon as possible.
¨
Thank you very much,
Mat

**Comment by cyb3rfox** [comment]
No worries at all. Thanks for your support.
